package cn.guangtong.model;



/**
 * 车辆状态表
 */
public class VehicleStatus {
	/**
	//gps_info
	gpsId
	alarmState '报警位状态'
	altitude '海拔高度'
	createDate '更新时间'
	direction '方向'
	gas '油量'
	latitude '纬度'
	location '对经纬度的地理位置解析' 
	longitude '经度'
	mileage '里程'
	plateNo '车牌号'
	recordVeloVity '行驶记录仪速度'
	runStatus '运行状态'
	sendTime '发送时间'
	simNo '车终端卡号'
	status '状态'
	valid 'GPS的定位状态，false代表没有定位,被屏蔽或找不到卫星'
	velocity'速度'

	//driver_info
	id '司机ID'
	dName '姓名'
	tel '司机手机'
	password '密码'
	face '头像'
	driverType '司机类型（0：个人；1：企业）'
	cooperationId '企业ID'
	idCardNum '身份证号'
	idCardFrontImg '身份证正面'
	idCardBackImg '身份证反面'
	idCardValidDate '身份证有效期'
	addr '现地址'
	driverClass '准驾车型'
	DLNum '驾驶证号'
	DLImg2 '驾驶证副本'
	DLImg '驾驶证图片'
	DLValidDate '驾驶证有效期'
	CCBPNum '上岗证号'
	CCBPImg '上岗证图片'
	CCBPValidDate '上岗证有效期'
	professionNum '从业资格证编号'
	professionImg '从业资格证'
	professionImg2 '从业资格证副本'
	professionCount '从业资格继续教育次数'
	professionValidDate '从业资格证有效期'
	professionYearCheck '从业资格定级年检'
	reviewTime '审核时间（不管通过不通过，都记录审核时的时间）'
	reviewStatus '审核状态。0：未审核，1：通过，-1：审核失败2:待审核；3：重新提交审核'
	reviewNote '审核备注'
	available '状态（1：正常；0：冻结）'
	cooperationAvailable '可用状态。1，可用，0：不可用，与cooperation表保持一致'
	registrationId
	EcontactTel
	Econtact
	iosCid '安卓设备号'
	androidCid 'IOS设备号'
	isdel '是否已删除(0:正常1:已删除)'
	defaultVehicleNum '默认车牌号'
	imageForm '图片来源(默认CMS1，APP0)'
	remarks '备注'
	lastEditor '最后修改人员'
	updateTime '修改时间'
	//vehicle_info
	//id '车辆编号ID'
	num '车牌号'
	modelId '车型id'
	engineNum '发动机号'
	VIN '车架号'
	vehicleImg '车辆照片'
	VMAvalidDate '车辆管理费有效期'
	brandModel '厂牌型号'
	vehicleLicenseImg '行驶证照片'
	operationLicenseImg '营运证照片'
	operationLicenseNum '营运证号'
	operationLicenseDate '营运证有效期'
	operationYearCheck '营运证定级年检'
	rankCheckDate '车辆定级年检'
	secondMaintainDate '车辆二级维护月份'
	TCICompany '交强险承保公司'
	TCINum '车辆强制保险单号'
	TCIValidDate '交强险有效期'
	TCITel '承保公司服务电话'
	VCICompany '商业险承保公司名称'
	VCIValidDate '商业保险有效期'
	VCINum '商业险保险单号'
	VCIType '商业投保类型???'
	VCITel '商业险联系电话'
	operationType '营运类型（企业?个体）:企业：1，个人：2'
	//cooperationId '所属企业/个体编号'
	//reviewTime '审核时间'
	//reviewStatus '审核状态0:待审核，1：通过，-1：拒绝'
	//reviewNote '审核信息备注'
	createTime '创建时间'
	//available '车辆状态：0：不可用（冻结），1：可用'
	//cooperationAvailable '企业可用状态，与企业表里保持一致'
	vehicleLicenseImg2 '行驶证副本'
	//isdel '是否已删除(0:正常1:已删除)'
	//receiveAutoSend '是否接收自动派单(0:不接收;1:接收)'
	simNo '北斗设备号'
	defaultDriverName '默认驾驶员姓名'
	//lastEditor '最后修改人员'
	updateTime '修改时间'
	//driver_online
	driverId '司机Id'
	vehicleId '车辆Id'
	onlineTime '上线时间'
	driverStatus '上线状态（0:下线；1：上线；2：已上车；3：在途;）'
	driverAvailable '司机可用状态（1:正常；0：冻结）'
	cooprationAvailable '企业可用状态（1：正常：0：冻结）'
	vTotalCapacity '总容量'
	vRemainCapacity '剩余容量'
	vehicleModel '车型'
	receiveAutoSend '是否接收自动派单(0:不接收;1:接收)'
	//longitude '经度'
	//latitude '纬度'
	positionUpdateTime '经纬度更新时间'**/
}